webtalk_init -webtalk_dir D:/VHDL_Projects/PipelinedSRC/PipelinedSRC.sim/sim_1/behav/xsim.dir/cfg_tb_top_src_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu May 05 17:08:04 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211053343_0_0_362" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0eef9c29-3904-46f6-8a84-bace7ccf86a7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "155984185a7b489696a02b933cafc701" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2694 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.51_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "27768_KB" -context "xsim\\usage"
webtalk_transmit -clientid 483139599 -regid "211053343_0_0_362" -xml D:/VHDL_Projects/PipelinedSRC/PipelinedSRC.sim/sim_1/behav/xsim.dir/cfg_tb_top_src_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/VHDL_Projects/PipelinedSRC/PipelinedSRC.sim/sim_1/behav/xsim.dir/cfg_tb_top_src_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/VHDL_Projects/PipelinedSRC/PipelinedSRC.sim/sim_1/behav/xsim.dir/cfg_tb_top_src_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
